In [1]:
import numpy as np
import pandas as pd

In [2]:

dataset=pd.read_csv("50_Startups.csv")

In [3]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [5]:
dataset.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [6]:
dataset.head(25)

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04

In [7]:
x.shape

NameError: name 'x' is not defined

In [8]:
x = dataset.iloc[:, 0:4]
y = dataset.iloc[:, 2]

In [9]:
x

    R&D Spend  Administration  Marketing Spend       State
0   165349.20       136897.80        471784.10    New York
1   162597.70       151377.59        443898.53  California
2   153441.51       101145.55        407934.54     Florida
3   144372.41       118671.85        383199.62    New York
4   142107.34        91391.77        366168.42     Florida
5   131876.90        99814.71        362861.36    New York
6   134615.46       147198.87              NaN  California
7   130298.13       145530.06        323876.68     Florida
8   120542.52       148718.95        311613.29    New York
9   123334.88       108679.17        304981.62  California
10  101913.08             NaN        229160.95     Florida
11  100671.96        91790.61        249744.55  California
12   93863.75       127320.38        249839.44     Florida
13   91992.39       135495.07        252664.93  California
14  119943.24       156547.42        256512.92     Florida
15  114523.61       122616.84        261776.23    New York
16   78013.11       121597.55        264346.06  California
17   94657.16       145077.58        282574.31    New York
18   91749.16       114175.79        294919.57     Florida
19   86419.70       153514.11             0.00    New York
20   76253.86       113867.30        298664.47  California
21   78389.47       153773.43        299737.29    New York
22   73994.56       122782.75        303319.26     Florida
23   67532.53       105751.03        304768.73     Florida
24   77044.01        99281.34        140574.81    New York
25   64664.71       139553.16        137962.62  California
26   75328.87       144135.98        134050.07     Florida
27   72107.60       127864.55        353183.81    New York
28   66051.52       182645.56        118148.20     Florida
29   65605.48       153032.06        107138.38    New York
30   61994.48       115641.28         91131.24     Florida
31   61136.38       152701.92         88218.23    New York
32   63408.86       129219.61         46085.25  California
33   55493.95       103057.49        214634.81     Florida
34   46426.07       157693.92        210797.67  California
35   46014.02        85047.44        205517.64    New York
36   28663.76       127056.21        201126.82     Florida
37   44069.95        51283.14        197029.42  California
38   20229.59        65947.93        185265.10    New York
39   38558.51        82982.09        174999.30  California
40   28754.33       118546.05        172795.67  California
41   27892.92        84710.77        164470.71     Florida
42   23640.93        96189.63        148001.11  California
43   15505.73       127382.30         35534.17    New York
44   22177.74       154806.14         28334.72  California
45    1000.23       124153.04          1903.93    New York
46    1315.46       115816.21        297114.46     Florida
47       0.00       135426.92             0.00  California
48     542.05        51743.15             0.00    New York
49       0.00       116983.80         45173.06  California

In [10]:
type("Marketing Spend")

str

In [11]:
dataset.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       49.000000        49.000000      50.000000
mean    73721.615600   121564.038163    212725.266735  112012.639200
std     45902.256482    28264.721000    122959.103760   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103057.490000    134050.070000   90138.902500
50%     73051.080000   122782.750000    214634.810000  107978.190000
75%    101602.800000   145077.580000    299737.290000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [12]:
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mode()[0],inplace = True)

In [13]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87             0.00  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [14]:
dataset.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [15]:
type("Administration")

str

In [16]:
dataset["Administration"].fillna(dataset["Administration"].mode()[0],inplace = True)

In [17]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87             0.00  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08        51283.14        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [18]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [19]:
dataset.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [20]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

NameError: name 'StandardScaler' is not defined

In [21]:
from sklearn.preprocessing import StandardScaler
d = StandardScaler()
p = d.fit_transform(p)

NameError: name 'p' is not defined

In [22]:
p

NameError: name 'p' is not defined

In [23]:
p = np.array([[1,2,3],[-52,8,10000],[4,5,6]])

In [24]:
p

array([[    1,     2,     3],
       [  -52,     8, 10000],
       [    4,     5,     6]])

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [26]:

regression=Sequential()

In [27]:
regression

In [28]:
x_train.shape()

NameError: name 'x_train' is not defined

In [29]:
x.train[0:5,:]

AttributeError: 'DataFrame' object has no attribute 'train'

In [30]:
x_train.shape

NameError: name 'x_train' is not defined

In [31]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

NameError: name 'x_train' is not defined

In [32]:
regression.add(Dense( units = 20 , kernel_initializer="random_uniform" , activation = "relu"))

WARNING:tensorflow:From C:\Users\utkar\Anaconda3\lib\site-packages\tensorflow\python\keras\initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [33]:
regression

In [34]:
x.shape

(50, 4)

In [35]:

regression.add(Dense( units = 40
                     , kernel_initializer="random_uniform" , activation = "relu"))

In [36]:
regression.add(Dense( units = 40
                     , kernel_initializer="random_uniform" , activation = "relu"))

In [37]:
x = dataset.iloc[:,1:].values
y = dataset.iloc[:,0:1].values

In [38]:
x

array([[136897.8, 471784.1, 'New York', 192261.83],
       [151377.59, 443898.53, 'California', 191792.06],
       [101145.55, 407934.54, 'Florida', 191050.39],
       [118671.85, 383199.62, 'New York', 182901.99],
       [91391.77, 366168.42, 'Florida', 166187.94],
       [99814.71, 362861.36, 'New York', 156991.12],
       [147198.87, 0.0, 'California', 156122.51],
       [145530.06, 323876.68, 'Florida', 155752.6],
       [148718.95, 311613.29, 'New York', 152211.77],
       [108679.17, 304981.62, 'California', 149759.96],
       [51283.14, 229160.95, 'Florida', 146121.95],
       [91790.61, 249744.55, 'California', 144259.4],
       [127320.38, 249839.44, 'Florida', 141585.52],
       [135495.07, 252664.93, 'California', 134307.35],
       [156547.42, 256512.92, 'Florida', 132602.65],
       [122616.84, 261776.23, 'New York', 129917.04],
       [121597.55, 264346.06, 'California', 126992.93],
       [145077.58, 282574.31, 'New York', 125370.37],
       [114175.79, 294919.57, 'Florida', 124266.9],
       [153514.11, 0.0, 'New York', 122776.86],
       [113867.3, 298664.47, 'California', 118474.03],
       [153773.43, 299737.29, 'New York', 111313.02],
       [122782.75, 303319.26, 'Florida', 110352.25],
       [105751.03, 304768.73, 'Florida', 108733.99],
       [99281.34, 140574.81, 'New York', 108552.04],
       [139553.16, 137962.62, 'California', 107404.34],
       [144135.98, 134050.07, 'Florida', 105733.54],
       [127864.55, 353183.81, 'New York', 105008.31],
       [182645.56, 118148.2, 'Florida', 103282.38],
       [153032.06, 107138.38, 'New York', 101004.64],
       [115641.28, 91131.24, 'Florida', 99937.59],
       [152701.92, 88218.23, 'New York', 97483.56],
       [129219.61, 46085.25, 'California', 97427.84],
       [103057.49, 214634.81, 'Florida', 96778.92],
       [157693.92, 210797.67, 'California', 96712.8],
       [85047.44, 205517.64, 'New York', 96479.51],
       [127056.21, 201126.82, 'Florida', 90708.19],
       [51283.14, 197029.42, 'California', 89949.14],
       [65947.93, 185265.1, 'New York', 81229.06],
       [82982.09, 174999.3, 'California', 81005.76],
       [118546.05, 172795.67, 'California', 78239.91],
       [84710.77, 164470.71, 'Florida', 77798.83],
       [96189.63, 148001.11, 'California', 71498.49],
       [127382.3, 35534.17, 'New York', 69758.98],
       [154806.14, 28334.72, 'California', 65200.33],
       [124153.04, 1903.93, 'New York', 64926.08],
       [115816.21, 297114.46, 'Florida', 49490.75],
       [135426.92, 0.0, 'California', 42559.73],
       [51743.15, 0.0, 'New York', 35673.41],
       [116983.8, 45173.06, 'California', 14681.4]], dtype=object)

In [39]:
y

array([[165349.2 ],
       [162597.7 ],
       [153441.51],
       [144372.41],
       [142107.34],
       [131876.9 ],
       [134615.46],
       [130298.13],
       [120542.52],
       [123334.88],
       [101913.08],
       [100671.96],
       [ 93863.75],
       [ 91992.39],
       [119943.24],
       [114523.61],
       [ 78013.11],
       [ 94657.16],
       [ 91749.16],
       [ 86419.7 ],
       [ 76253.86],
       [ 78389.47],
       [ 73994.56],
       [ 67532.53],
       [ 77044.01],
       [ 64664.71],
       [ 75328.87],
       [ 72107.6 ],
       [ 66051.52],
       [ 65605.48],
       [ 61994.48],
       [ 61136.38],
       [ 63408.86],
       [ 55493.95],
       [ 46426.07],
       [ 46014.02],
       [ 28663.76],
       [ 44069.95],
       [ 20229.59],
       [ 38558.51],
       [ 28754.33],
       [ 27892.92],
       [ 23640.93],
       [ 15505.73],
       [ 22177.74],
       [  1000.23],
       [  1315.46],
       [     0.  ],
       [   542.05],
       [     0.  ]])

In [40]:
regression.compile(optimizer = "adam",loss = "binary_crosentropy",metrics = ["accuracy"])

In [41]:
regression.fit(x_train,y_train , epochs = 25)

NameError: name 'x_train' is not defined

In [42]:
regression.add(Dense( units = 1 , kernel_initializer="random_uniform" , activation = "sigmoid"))

In [43]:
regression.fit(x_train,y_train , epochs = 25)

NameError: name 'x_train' is not defined

In [44]:
regression.fit(x_train,y_train , epochs = 25)

NameError: name 'x_train' is not defined

In [ ]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [45]:
regression.fit(x ,y , epochs = 30)

TypeError: Unable to build `Dense` layer with non-floating point dtype <dtype: 'string'>

In [46]:
regression.fit(x_train, y_train,epochs = 30)

NameError: name 'x_train' is not defined

In [47]:
ypred =regression.predict(x_test)

NameError: name 'x_test' is not defined

In [48]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)

NameError: name 'x_train' is not defined

In [49]:
from sklearn.preprocessing import StandardScaler
d = StandardScaler()
p = d.fit_transform(p)

In [57]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

NameError: name 'x_train' is not defined

In [58]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

NameError: name 'x_train' is not defined

In [59]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)

NameError: name 'x_train' is not defined

In [60]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)

NameError: name 'x_train' is not defined

In [61]:
regression.compile(optimizer = "adam",loss = "binary_crossentropy",metrics = ["accuracy"])

In [69]:

regression.fit(x_train ,y_test , epochs = 50)

ValueError: ('Error when checking model target: expected no data, but got:', array([[ 66051.52],
       [100671.96],
       [101913.08],
       [ 27892.92],
       [153441.51],
       [ 72107.6 ],
       [ 20229.59],
       [ 61136.38],
       [ 73994.56],
       [142107.34],
       [ 55493.95],
       [ 46014.02],
       [ 75328.87],
       [ 46426.07],
       [ 91749.16],
       [130298.13],
       [119943.24]]))

In [68]:
ypred = regression.predict(x_test)

IndexError: list index out of range

In [67]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

ValueError: could not convert string to float: 'New York'

In [65]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

In [66]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

In [70]:
regression.compile(optimizer = "adam",loss = "binary_crossentropy",metrics = ["accuracy"])

In [73]:
regression.fit(x_train, y_train,epochs = 350)

ValueError: ('Error when checking model target: expected no data, but got:', array([[  1000.23],
       [   542.05],
       [ 65605.48],
       [114523.61],
       [ 61994.48],
       [ 63408.86],
       [ 78013.11],
       [ 23640.93],
       [ 76253.86],
       [ 15505.73],
       [120542.52],
       [ 91992.39],
       [ 64664.71],
       [131876.9 ],
       [ 94657.16],
       [ 28754.33],
       [     0.  ],
       [162597.7 ],
       [ 93863.75],
       [ 44069.95],
       [ 77044.01],
       [134615.46],
       [ 67532.53],
       [ 28663.76],
       [ 78389.47],
       [ 86419.7 ],
       [123334.88],
       [ 38558.51],
       [  1315.46],
       [144372.41],
       [165349.2 ],
       [     0.  ],
       [ 22177.74]]))

In [74]:
ypred = regression.predict(x_test)

IndexError: list index out of range

In [75]:
ypred

NameError: name 'ypred' is not defined